server:
  port: 8002
# 应用名称
spring:
  application:
    name: chain-service
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  devtools:
    livereload:
      port: 35751
  profiles:
    include: feign, mysql, nacos, spring, jwt, ribbon

chain:
  remote-address: localhost:8888
