server:
  port: 8080
# 应用名称
spring:
  application:
    name: demo-service
  main:
    allow-circular-references: true
  devtools:
    livereload:
      port: 35750
  profiles:
    include: feign, mysql, nacos, spring, jwt, ribbon
