server:
  port: 8060
# 应用名称
spring:
  application:
    name: carbon-trade-service
  main:
    allow-circular-references: true
  devtools:
    livereload:
      port: 35753
  profiles:
    include: feign, mysql, nacos, spring, jwt, ribbon, dubbo
