spring:
  config:
    activate:
      on-profile: nacos
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        # 如果是public，就不用填了
        namespace:
