server:
  port: 8079
# 应用名称
spring:
  application:
    name: auth-service
  main:
    allow-circular-references: true
  devtools:
    livereload:
      port: 35732
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        # 如果是public，就不用填了
        namespace:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:33060/cloud_test?serverTimezone=UTC
    username: root
    password: RrOoOoTt!@#123.
debug: true
