server:
  port: 8079
# 应用名称
spring:
  application:
    name: auth-service
  main:
    allow-circular-references: true
  devtools:
    livereload:
      port: 35732
  profiles:
    include: feign, mysql, nacos, spring, jwt, ribbon
