server:
  port: 8980
# 应用名称
spring:
  application:
    name: carbon-cal-service
  main:
    allow-circular-references: true
  devtools:
    livereload:
      port: 35751
  profiles:
    include: feign, mysql, nacos, spring, jwt, ribbon, dubbo
